export const allProductions = [
	{
		id: 1,
		title: "Avcı Interior",
		img: "/images/productions/interior.jpg",
		url: "https://vimeo.com/451153012",
	},
	{
		id: 2,
		title: "The Passion",
		img: "/images/productions/the-passion.jpg",
		url: "https://vimeo.com/399683774",
	},
	{
		id: 3,
		title: "Slow Down",
		img: "/images/productions/slow-down.jpg",
		url: "https://vimeo.com/389929131",
	},
	{
		id: 4,
		title: "#artwithus | agt",
		img: "/images/productions/art-with-us.jpg",
		url: "https://vimeo.com/389923180",
	},
	{
		id: 5,
		title: "Showreel",
		img: "/images/productions/showreel.jpg",
		url: "https://vimeo.com/381624477",
	},
	{
		id: 6,
		title: "Lunar Circus Promo Film",
		img: "/images/productions/lunar.jpg",
		url: "https://vimeo.com/374399400",
	},
	{
		id: 7,
		title: "SPX - How Big",
		img: "/images/productions/spx.jpg",
		url: "https://vimeo.com/374397445",
	},
	{
		id: 8,
		title: "TANDEM DANCE THEATRE PROMO FILM",
		img: "/images/productions/tandem-promo.jpg",
		url: "https://vimeo.com/365480996",
	},
	{
		id: 9,
		title: "NORTHMEN 1. YIL FILM",
		img: "/images/productions/northmen.jpg",
		url: "https://vimeo.com/363542216",
	},
	{
		id: 10,
		title: "TANDEM DANCE THEATRE TEASER",
		img: "/images/productions/tandem-promo-teaser.jpg",
		url: "https://vimeo.com/363547177",
	},
	{
		id: 11,
		title: "FINAL JAM RECAP",
		img: "/images/productions/final-jam-recap.jpg",
		url: "https://vimeo.com/357361066",
	},
	{
		id: 12,
		title: "KRAFT FESTIVAL",
		img: "/images/productions/kraft-festival.jpg",
		url: "https://vimeo.com/348397100",
	},
	{
		id: 13,
		title: "RAPID DANCE",
		img: "/images/productions/rapid-dance.jpg",
		url: "https://vimeo.com/347025216",
	},
	{
		id: 14,
		title: "SPA SOUL | HYATT CENTRİC LEVENT İSTANBUL",
		img: "/images/productions/spa-soul.jpg",
		url: "https://vimeo.com/336091625",
	},
	{
		id: 15,
		title: "RENEKA R80 COMMERCIAL",
		img: "/images/productions/reneka.jpg",
		url: "https://vimeo.com/323702052",
	},
	{
		id: 16,
		title: "2019 SHOWREEL",
		img: "/images/productions/2019-reel.jpg",
		url: "https://vimeo.com/331442093",
	},
	{
		id: 17,
		title: "CRYSTAL GELATO FILM",
		img: "/images/productions/crystal-gelato.jpg",
		url: "https://vimeo.com/312514219",
	},
	{
		id: 18,
		title: "THE SUDD COFFEE – CHRISTMAS FILM",
		img: "/images/productions/christmas.jpg",
		url: "https://vimeo.com/308987488",
	},
	{
		id: 19,
		title: "CARDI B – I LIKE IT | HİPHOP | CHOREOGRAPHY MUSIC CLIP",
		img: "/images/productions/i-like-it-like-that.jpg",
		url: "https://vimeo.com/371645946",
	},
	{
		id: 20,
		title: "ZAYN – FINGERS | DANCE PERFORMANCE",
		img: "/images/productions/fingers.jpg",
		url: "https://vimeo.com/381060937",
	},
	{
		id: 21,
		title: "APES**T DANCE CHOREOGRAPHY",
		img: "/images/productions/apeshit.jpg",
		url: "https://vimeo.com/301697239",
	},
	{
		id: 22,
		title: "CRYSTAL & SMACH EVENT FILM",
		img: "/images/productions/crystal-event.jpg",
		url: "https://vimeo.com/312514219",
		// youtube
	},
	{
		id: 23,
		title: "AŞKIN HALI TOZ DUMAN – MUSIC CLIP",
		img: "/images/productions/askin-hali.jpg",
		url: "https://vimeo.com/273713790",
	},
	{
		id: 24,
		title: "DRONE THE HOTEL | CALISTA LUXURY HOTEL",
		img: "/images/productions/drone.jpg",
		url: "https://vimeo.com/301711984",
	},
	{
		id: 25,
		title: "TENNIS LIFE | CALISTA LUXURY HOTEL",
		img: "/images/productions/tennis.jpg",
		url: "https://vimeo.com/301712700",
	},
	{
		id: 26,
		title: "TIMELAPSE MOOD | CALISTA LUXURY HOTEL",
		img: "/images/productions/timelapse.jpg",
		url: "https://vimeo.com/301712934",
	},
	{
		id: 27,
		title: "GYMFACTORY FITNESS CLUB | HYPER SPORT",
		img: "/images/productions/hyper-sport.jpg",
		url: "https://vimeo.com/301718360",
	},
	{
		id: 28,
		title: "GYMFACTORY FITNESS CLUB | SPORT TİME",
		img: "/images/productions/sport-time.jpg",
		url: "https://vimeo.com/301718451",
	},
	{
		id: 29,
		title: "REDBULL | KICK IT",
		img: "/images/productions/kick-it.jpg",
		url: "https://vimeo.com/301719024",
	},
]

export const commercialProductions = [
	{
		id: 1,
		title: "Avcı Interior",
		img: "/images/productions/interior.jpg",
		url: "https://vimeo.com/451153012",
	},
	{
		id: 2,
		title: "The Passion",
		img: "/images/productions/the-passion.jpg",
		url: "https://vimeo.com/399683774",
	},
	{
		id: 3,
		title: "#artwithus | agt",
		img: "/images/productions/art-with-us.jpg",
		url: "https://vimeo.com/389923180",
	},
	{
		id: 4,
		title: "Showreel",
		img: "/images/productions/showreel.jpg",
		url: "https://vimeo.com/381624477",
	},
	{
		id: 5,
		title: "Lunar Circus Promo Film",
		img: "/images/productions/lunar.jpg",
		url: "https://vimeo.com/374399400",
	},
	{
		id: 6,
		title: "SPX - How Big",
		img: "/images/productions/spx.jpg",
		url: "https://vimeo.com/374397445",
	},
	{
		id: 7,
		title: "TANDEM DANCE THEATRE PROMO FILM",
		img: "/images/productions/tandem-promo.jpg",
		url: "https://vimeo.com/365480996",
	},
	{
		id: 8,
		title: "NORTHMEN 1. YIL FILM",
		img: "/images/productions/northmen.jpg",
		url: "https://vimeo.com/363542216",
	},
	{
		id: 9,
		title: "TANDEM DANCE THEATRE TEASER",
		img: "/images/productions/tandem-promo-teaser.jpg",
		url: "https://vimeo.com/363547177",
	},
	{
		id: 10,
		title: "FINAL JAM RECAP",
		img: "/images/productions/final-jam-recap.jpg",
		url: "https://vimeo.com/357361066",
	},
	{
		id: 11,
		title: "KRAFT FESTIVAL",
		img: "/images/productions/kraft-festival.jpg",
		url: "https://vimeo.com/348397100",
	},
	{
		id: 12,
		title: "RAPID DANCE",
		img: "/images/productions/rapid-dance.jpg",
		url: "https://vimeo.com/347025216",
	},
	{
		id: 13,
		title: "SPA SOUL | HYATT CENTRİC LEVENT İSTANBUL",
		img: "/images/productions/spa-soul.jpg",
		url: "https://vimeo.com/336091625",
	},
	{
		id: 14,
		title: "RENEKA R80 COMMERCIAL",
		img: "/images/productions/reneka.jpg",
		url: "https://vimeo.com/323702052",
	},
	{
		id: 15,
		title: "SHOWREEL",
		img: "/images/productions/2019-reel.jpg",
		url: "https://vimeo.com/331442093",
	},
	{
		id: 16,
		title: "CRYSTAL GELATO FILM",
		img: "/images/productions/crystal-gelato.jpg",
		url: "https://vimeo.com/312514219",
	},
	{
		id: 17,
		title: "THE SUDD COFFEE – CHRISTMAS FILM",
		img: "/images/productions/christmas.jpg",
		url: "https://vimeo.com/308987488",
	},
	{
		id: 18,
		title: "CRYSTAL & SMACH EVENT FIL",
		img: "/images/productions/crystal-event.jpg",
		url: "https://vimeo.com/312514219",
		// youtube
	},
]

export const creativeProductions = [
	{
		id: 1,
		title: "DRONE THE HOTEL | CALISTA LUXURY HOTEL",
		img: "/images/productions/drone.jpg",
		url: "https://vimeo.com/301711984",
	},
	{
		id: 2,
		title: "TENNIS LIFE | CALISTA LUXURY HOTEL",
		img: "/images/productions/tennis.jpg",
		url: "https://vimeo.com/301712700",
	},
	{
		id: 3,
		title: "TIMELAPSE MOOD | CALISTA LUXURY HOTEL",
		img: "/images/productions/timelapse.jpg",
		url: "https://vimeo.com/301712934",
	},
	{
		id: 4,
		title: "GYMFACTORY FITNESS CLUB | HYPER SPORT",
		img: "/images/productions/hyper-sport.jpg",
		url: "https://vimeo.com/301718360",
	},
	{
		id: 5,
		title: "GYMFACTORY FITNESS CLUB | SPORT TİME",
		img: "/images/productions/sport-time.jpg",
		url: "https://vimeo.com/301718451",
	},
	{
		id: 6,
		title: "REDBULL | KICK IT",
		img: "/images/productions/kick-it.jpg",
		url: "https://vimeo.com/301719024",
	},
]

export const musicVideoProductions = [
	{
		id: 1,
		title: "Slow Down",
		img: "/images/productions/slow-down.jpg",
		url: "https://vimeo.com/389929131",
	},
	{
		id: 2,
		title: "CARDI B – I LIKE IT | HİPHOP | CHOREOGRAPHY MUSIC CLIP",
		img: "/images/productions/i-like-it-like-that.jpg",
		url: "https://vimeo.com/371645946",
	},
	{
		id: 3,
		title: "ZAYN – FINGERS | DANCE PERFORMANCE",
		img: "/images/productions/fingers.jpg",
		url: "https://vimeo.com/381060937",
	},
	{
		id: 4,
		title: "APES**T DANCE CHOREOGRAPHY",
		img: "/images/productions/apeshit.jpg",
		url: "https://vimeo.com/301697239",
	},
	{
		id: 5,
		title: "AŞKIN HALI TOZ DUMAN – MUSIC CLIP",
		img: "/images/productions/askin-hali.jpg",
		url: "https://vimeo.com/273713790",
	},
]
